### ISSUE TITLE
Be compliant with biocontainers labels

### ISSUE THREAD

**Issue by pcm32** [phnmnl/jenkins-scripts#1]
Thanks for this excellent work @pierrickrogermele !

Can I suggest that we use LABEL instead of ENV directly, to start adhering to some of BioContainers labeling strategy. What they are proposing is something like this:

```dockerfile
LABEL version="3"
LABEL software.version="1.9.0"
```

Where the first one is the container version. See an example [here](https://github.com/BioContainers/containers/blob/master/abyss/1.9.0/Dockerfile).

**Comment by pkrog** [comment]
If you look at the Dockerfile of container-lcmsmatching, you will see that I use the ENV var to get the proper tool version with git. I think this is a good practise. You wouldn't be able to do that by only using LABEL.
However, I could modify the script so it first look for ENV definitions and then for LABEL, so both would be possible.

**Comment by pcm32** [comment]
I think that that would be a nice approach, be able to use both. I would love to hear Yasset's opinion on this. I have invited him to the organization, I'll tag him when he has accepted.

**Comment by pkrog** [comment]
I've implemented it. It first searches for ENV definition, then for LABEL definition.
