### ISSUE TITLE
Allow Dockerfile path to be passed as an argument

### ISSUE THREAD

**Issue by pcm32** [phnmnl/jenkins-scripts#2]
I would suggest that we receive the Dockerfile relative path as shell variable which we can inject, instead of assuming that it is sitting in the working directory, or that we can set instead the working directory in the same way. This is because some Dockerfiles might not be in the root of the git repo. I think so far most of them are, but we have never enforced this.

Thanks!

**Comment by sneumann** [comment]
They are not in root for the BioC containers, https://github.com/phnmnl/bioc_docker/tree/master/out/devel_metabolomics

**Comment by pkrog** [comment]
We could search for the Dockerfile file recursively from root dir, using find command. If we find two Dockerfiles we emit an error.
In addition, to solve cases where several Dockerfiles are present, we could take the Dockerfile path as an env var.

**Comment by pcm32** [comment]
I think that using find might be an extra complication, but up to you, as long as we have the option of having an env. var injected, which from Jenkins is very easy to do. I would expect that if the env var is set, then you don't execute the find command.

**Comment by pkrog** [comment]
Done. Use MAKE_VERSIONS_DOCKERFILE env var to define custom Dockerfile path.
I've not implemented the `find` solution. Too complex to test.
