### ISSUE TITLE
Emit tag as an environment variable

### ISSUE THREAD

**Issue by pcm32** [phnmnl/jenkins-scripts#3]
By using this method I would expect to get rid of the PhenoMeNal_versions.txt file altogether. In that case, I would rather have this script producing the required environmental variables that should be used down the line to set the tag: `${TOOL_VERSION}_cv${CONTAINER_VERSION}`.

**Comment by pkrog** [comment]
I don't understand how this would be possible. A program cannot define env var for its calling/parent program/shell. We would need to define a new plugin as the inject plugin we are using. Is that what you want ?
Alternatively, I could define a CONTAINER_TAG var inside PhenoMeNal_versions.txt, so it would be easier to set tag inside Jenkins task.

**Comment by pcm32** [comment]
If a shell script exports a variable, this can be seen from the outside. We
would need to check how isolated are the different build tasks in Jenkins.

**Comment by pkrog** [comment]
If you call a shell script A from say an interactive shel B, no env var exported from A can be seen from this interactive shell B. This is because only a copy of the environment is passed to A. It is the same if B is a shell script, script, or program.
The only way to get env var in B is to source A.

**Comment by pkrog** [comment]
Done in branch feature/tagprefix, merged into develop and master.

**Comment by pcm32** [comment]
Yes, you're right on the sourcing part. Then if we are not emitting the tag, we can just add an additional field to `PhenoMeNal_Versions.txt` file with the additional information. In this case, my interest was to add a prefix or postfix if the build was emanating from the either the development or master branches. So that we could tell then from the docker image tag whether this is a release (from master) or development version.

I would add something like a "_dev" suffix to the tag if we are building from development, and no suffix if this is a release build. What do you think?

For this the make script needs to be aware of the variable injected by Jenkins containing the git branch, and producing the prefix/suffix if adequate.

**Comment by pkrog** [comment]
I've already done. See issue "Consume branch environment variable". I've put a prefix tag (dev_) as was discussed in this issue. The prefix is added if the command `git status` returns the branch name 'develop'.
