### ISSUE TITLE
Consume branch environment variable

### ISSUE THREAD

**Issue by pcm32** [phnmnl/jenkins-scripts#4]
As discussed with @sneumann , we would like at some point to be able to tell from the docker tag whether an image was built from the development branch (less stable, bleeding edge), or from the master branch (a release version). In this way we will be able to provision an stable Galaxy container, pointing to stable versions of tools, and a bleeding edge versions for developers working on tool improvement. For this we would like to add something on the tag, could be for instance, appending a `dev` string to the tag:

```
dev_v${TOOL_VERSION}_cv${CONTAINER_VERSION}.${BUILD_NUMBER}
```

to trigger this, we need to make use of the variable `$GIT_BRANCH` exposed during the Jenkins build process by the [Git plugin](https://wiki.jenkins-ci.org/display/JENKINS/Git+Plugin) (see the environmental variables part). Altogether this could mean as well that instead of emitting the `TOOL_VERSION` and `CONTAINER_VERSION` variables (as suggested in #3 ), we could already emit as environment variable the complete tag, including the build number, and adding the dev if we are building from the development branch.

**Comment by pkrog** [comment]
So you would like to have the master branch of the container repos to use the master branch of the tool repos, and a devel branch of the container repos to use a devel branch (whatever it is named) of the tool repos ?
We would then base ourselves on the name of the container repos branch to know if it is release or devel ?

**Comment by pcm32** [comment]
Exactly! and we would influence the tag based on that.

**Comment by pkrog** [comment]
Done in branch feature/tagprefix, merged into master and develop.
