### ISSUE TITLE
test_cmds.txt not robust

### ISSUE THREAD

**Issue by korseby** [phnmnl/jenkins-scripts#7]
Hi @pierrickrogermele and @pcm32,

while testing r-base (https://github.com/phnmnl/container-rbase/blob/develop/test_cmds.txt), the automated test fails in Jenkins when:
1) test_cmds.txt has a newline
2) test_cmds.txt has more than one line

This is the error output:

```
+ bash test-built-container docker-registry-v2.local:30750/phnmnl/rbase

/usr/bin/Rscript
/usr/bin/R
Fatal error: you must specify '--save', '--no-save' or '--vanilla'
ARGUMENT '/usr/bin/runTest1.R' __ignored__

Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

Please fix.

@sneumann  @c-ruttkies  This could be interesting for you as well.

Best wishes

**Comment by pcm32** [comment]
Thanks for this @korseby !

I should mention though that `runTest1.*` is not supposed to be invoked from test_cmds, these are entirely separate testing strategies (you could check though for its presence, that should be fine, but not trigger execution). If you change the name of `runTest1.sh` to something else, make sure that the testing job on Jenkins reflects this.
